namespace WpfApp
{
    // All Calculator methods were generated by AI using Github Copilot.
    // Copilot is an AI pair programmer that helps you write code faster and with less effort.
    public static class Calculator
    {
        // Add two numbers
        public static int Add(int a, int b)
        {
            return a + b;
        }
        // Substract two numbers
        public static int Substract(int a, int b)
        {
            return a - b;
        }
        // Multiply two numbers
        public static int Multiply(int a, int b)
        {
            return a * b;
        }
        // Divide two numbers
        public static double Divide(int a, int b)
        {
            return a / b;
        }
    }
}